-- Retrieve all data from each table
SELECT * FROM DEPARTMENT;
SELECT * FROM STUDENT;
SELECT * FROM FACULTY;
SELECT * FROM COURSE;
SELECT * FROM ENROLLMENT;
SELECT * FROM EXAM;
SELECT * FROM CLASSROOM;
SELECT * FROM SCHEDULE;
